[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[functions]]
  path = "netlify/functions/proxy.js"
  [functions.settings]
    max_body_size = 15

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200